export const EXPIRES_IN = 3000
export enum STATUS {
    PENDING = 'PENDING',
    UPLOADING='UPLOADING',
    PROCESSING = 'PROCESSING',
    PROCESSED = 'PROCESSED',
    FAILED = 'FAILED'
}
export enum TRANSFORMATION_TYPE {
  ROTATE="ROTATE",
  RESIZE="RESIZE",
  FORCE_RESIZE="FORCE_RESIZE",
  CONVERT="CONVERT"
}